### ISSUE TITLE
Links to papers

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/mhc#13]
http://biorxiv.org/content/early/2016/05/22/054775.full.pdf+html

https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-016-0288-x

**Comment by rudolphyo** [comment]
[ref with rtf table](http://help.iedb.org/hc/en-us/articles/114094151811-Selecting-thresholds-cut-offs-for-MHC-class-I-and-II-binding-predictions)
[article where thresholds set](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3872965/)

**Comment by vadimnazarov** [comment]
https://arxiv.org/pdf/1512.03385.pdf
https://arxiv.org/pdf/1605.07146.pdf
